export const refundPolicy = {
  ko: [
    {
      title: "1. 환불 정책 개요",
      content: "본 서비스는 디지털 문서(PDF)를 생성하여 제공하는 서비스입니다. 서비스 특성상 디지털 문서 생성이 완료되어 다운로드 또는 이메일 전송이 가능한 상태가 된 이후에는 환불이 불가합니다."
    },
    {
      title: "2. 환불 가능 조건",
      content: "결제 후 아직 문서를 생성(다운로드)하지 않은 상태에서 단순 변심에 의한 환불 요청 시 전액 환불이 가능합니다. 단, 결제일로부터 7일 이내에 요청해야 합니다."
    },
    {
      title: "3. 환불 불가 조건",
      content: "- 이미 시스템을 통해 PDF 문서 생성이 완료된 경우\n- 결제 후 7일이 경과한 경우\n- 크레딧을 사용하여 이미 서비스를 이용한 경우"
    },
    {
      title: "4. 환불 요청 방법",
      content: "환불을 원하시는 경우 info@hikoreaforms.com 으로 결제 내역과 함께 문의해 주시기 바랍니다."
    }
  ],
  en: [
    {
      title: "1. Refund Policy Overview",
      content: "This service provides digital document (PDF) generation. Due to the nature of digital goods, refunds are not possible once the document has been successfully generated and made available for download or email."
    },
    {
      title: "2. Conditions for Refund",
      content: "A full refund is possible if you request it before any document has been generated using your credits. The request must be made within 7 days of the payment date."
    },
    {
      title: "3. Non-Refundable Conditions",
      content: "- The PDF document has already been generated by the system\n- More than 7 days have passed since the payment date\n- The credits have already been consumed"
    },
    {
      title: "4. How to Request a Refund",
      content: "To request a refund, please contact info@hikoreaforms.com with your payment details."
    }
  ],
  ru: [
    {
      title: "1. Общие положения",
      content: "Данный сервис предоставляет услуги по созданию цифровых документов (PDF). В связи с особенностями цифровых товаров, возврат средств невозможен после того, как документ был сгенерирован и стал доступен для скачивания."
    },
    {
      title: "2. Условия возврата",
      content: "Полный возврат средств возможен в случае, если вы запросили его до момента создания документа с использованием ваших кредитов. Запрос должен быть отправлен в течение 7 дней с момента оплаты."
    },
    {
      title: "3. Условия отказа в возврате",
      content: "- Документ PDF уже был успешно сгенерирован системой\n- Прошло более 7 дней с момента оплаты\n- Кредиты уже были использованы для услуг"
    },
    {
      title: "4. Как запросить возврат",
      content: "Для запроса возврата средств, пожалуйста, свяжитесь с нами по адресу info@hikoreaforms.com, указав детали платежа."
    }
  ]
};
